### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by cliffordp** [hasinhayder/plugin-boilerplate-code-generator#4]
I just tried http://codegen.kickapz.com/ and
- the `includes` directory only has index.php -- so it's missing activator, deactivator, i18n, loader, and name.php
- the `languages` directory .pot file doesn't get renamed. It is called `plugin-name.pot` (I'm assuming it's supposed to have been renamed)

Hope this helps.

**Comment by hasinhayder** [comment]
It has been fixed now. Repo updated to the latest code
